apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "precog.fullname" . }}
  labels:
    {{- include "precog.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "precog.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "precog.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "precog.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: {{ include "precog.fullname" . }}
          {{- if .Values.config.apiKey }}
          env:
            - name: PRECOG_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "precog.fullname" . }}
                  key: api-key
          {{- end }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
