{{- if .Values.config.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "precog.fullname" . }}
  labels:
    {{- include "precog.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.config.apiKey | quote }}
{{- end }}
